// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"database/sql"
	"github.com/Promacanthus/Go-000/Week04/pkg/biz"
	"github.com/Promacanthus/Go-000/Week04/pkg/dao"
	"github.com/Promacanthus/Go-000/Week04/pkg/service"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "time/tzdata"
)

// Injectors from wire.go:

func InitHandler(db *sql.DB) service.Handler {
	repo := dao.NewRepo(db)
	stringService := biz.NewStringService(repo)
	handler := service.NewHandler(stringService)
	return handler
}
